FROM apache/airflow:3.2.2

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    docker.io docker-compose-plugin \
    && rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt